name: Build Terrakube Backend

on:
  push:
    branches:
      - main

jobs:
  build-jammy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - uses: actions/checkout@v4
    - name: Development
      run: echo "Hello Development"
  
  build-jammy-prod:
    runs-on: ubuntu-latest
    needs: build-jammy
    environment: Production
    steps:
    - uses: actions/checkout@v4
    - name: Production
      run: echo "Hello Production"
